#!/usr/bin/env python3
"""
Cross-platform build-and-test for cxx-shared-test (bundled cdylib).
Run from anywhere; all paths are derived from this script's location.

Known issue (macOS): rustc passes -exported_symbols_list to ld64 when
building a cdylib, restricting exports to Rust-known symbols.  The C++
bridge wrappers generated by cxx-build are not in that list and are
therefore suppressed from the dylib's export table even when the archive
is force-loaded.  This test is expected to fail on macOS until a proper
fix is found (e.g. augmenting rustc's export list from build.rs).
"""

import os
import platform
import subprocess
from pathlib import Path


def run(cmd, **kwargs):
    print("==>", " ".join(str(a) for a in cmd))
    subprocess.run(cmd, check=True, **kwargs)


def main():
    crate_dir = Path(__file__).resolve().parent.parent
    repo_root = crate_dir.parent.parent
    lib_dir = repo_root / "target" / "debug"
    bridge_inc = repo_root / "target" / "cxxbridge" / "cxx-shared-test" / "src"
    rust_inc = repo_root / "target" / "cxxbridge" / "rust"
    consumer = crate_dir / "consumer" / "main.cc"

    run(["cargo", "build"], cwd=crate_dir)

    os_name = platform.system()
    if os_name == "Windows":
        run(
            [
                "cl.exe",
                "/EHsc",
                "/std:c++17",
                str(consumer),
                "/DCXX_SHARED",
                "/DCXX_API_SHARED",
                f"/I{bridge_inc}",
                f"/I{rust_inc}",
                str(lib_dir / "cxx_shared_test.dll.lib"),
                f"/Fe:{crate_dir / 'test_app.exe'}",
            ],
            cwd=crate_dir,
        )
        env = os.environ | {
            "PATH": str(lib_dir) + os.pathsep + os.environ.get("PATH", "")
        }
        run([str(crate_dir / "test_app.exe")], env=env)
    else:
        run(
            [
                "g++",
                "-std=c++17",
                str(consumer),
                "-DCXX_SHARED",
                "-DCXX_API_SHARED",
                f"-I{bridge_inc}",
                f"-I{rust_inc}",
                f"-L{lib_dir}",
                "-lcxx_shared_test",
                f"-Wl,-rpath,{lib_dir}",
                "-o",
                str(crate_dir / "test_app"),
            ],
            cwd=crate_dir,
        )
        run([str(crate_dir / "test_app")])


if __name__ == "__main__":
    main()
